[build]
  publish = "dist"  # Output directory for static files
  functions = "netlify/functions"  # Directory where SSR functions are stored

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
